// Code generated by "stringer -type=downloadStatus"; DO NOT EDIT.

package downloader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[statusComplete-0]
	_ = x[statusError-1]
	_ = x[statusStopped-2]
}

const _downloadStatus_name = "statusCompletestatusErrorstatusStopped"

var _downloadStatus_index = [...]uint8{0, 14, 25, 38}

func (i downloadStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_downloadStatus_index)-1 {
		return "downloadStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _downloadStatus_name[_downloadStatus_index[idx]:_downloadStatus_index[idx+1]]
}
